/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rafam
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAC = new javax.swing.JButton();
        btnMaisMenos = new javax.swing.JButton();
        btnPorcentagem = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        btn7value = new javax.swing.JButton();
        btn8value = new javax.swing.JButton();
        btn9value = new javax.swing.JButton();
        btnMultiplicacao = new javax.swing.JButton();
        btn4value = new javax.swing.JButton();
        btn5value = new javax.swing.JButton();
        btn6value = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        btn1value = new javax.swing.JButton();
        btn2value = new javax.swing.JButton();
        btn3value = new javax.swing.JButton();
        btnAdicao = new javax.swing.JButton();
        btn0value = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(440, 560));

        tfValor.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        tfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValor.setText("0,00");

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        btnAC.setText("AC");
        jPanel1.add(btnAC);

        btnMaisMenos.setText("+/-");
        jPanel1.add(btnMaisMenos);

        btnPorcentagem.setText("%");
        jPanel1.add(btnPorcentagem);

        btnDivisao.setText("/");
        jPanel1.add(btnDivisao);

        btn7value.setText("7");
        btn7value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7valueActionPerformed(evt);
            }
        });
        jPanel1.add(btn7value);

        btn8value.setText("8");
        jPanel1.add(btn8value);

        btn9value.setText("9");
        jPanel1.add(btn9value);

        btnMultiplicacao.setText("*");
        jPanel1.add(btnMultiplicacao);

        btn4value.setText("4");
        jPanel1.add(btn4value);

        btn5value.setText("5");
        jPanel1.add(btn5value);

        btn6value.setText("6");
        jPanel1.add(btn6value);

        btnSubtracao.setText("-");
        jPanel1.add(btnSubtracao);

        btn1value.setText("1");
        btn1value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1valueActionPerformed(evt);
            }
        });
        jPanel1.add(btn1value);

        btn2value.setText("2");
        jPanel1.add(btn2value);

        btn3value.setText("3");
        jPanel1.add(btn3value);

        btnAdicao.setText("+");
        jPanel1.add(btnAdicao);

        btn0value.setText("0");
        jPanel1.add(btn0value);

        btnPonto.setText(".");
        jPanel1.add(btnPonto);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jPanel1.add(btnFechar);

        btnResultado.setText("=");
        jPanel1.add(btnResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfValor)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1valueActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btn7valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7valueActionPerformed

    private void digita(String caractere){
        tfValor
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0value;
    private javax.swing.JButton btn1value;
    private javax.swing.JButton btn2value;
    private javax.swing.JButton btn3value;
    private javax.swing.JButton btn4value;
    private javax.swing.JButton btn5value;
    private javax.swing.JButton btn6value;
    private javax.swing.JButton btn7value;
    private javax.swing.JButton btn8value;
    private javax.swing.JButton btn9value;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAdicao;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnMaisMenos;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnPorcentagem;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
